import { describe, expect, test } from 'bun:test';
import { PORTED_APP_SKILL_CODES } from '@/game/ported-app-skill-codes';

describe('ported app.shogi skill coverage', () => {
  test('covers the app.shogi move-skill families used by online matching', () => {
    expect(new Set(PORTED_APP_SKILL_CODES)).toEqual(
      new Set([
        'FLAME',
        'ENN',
        'FIRE',
        'FIR',
        'TREASURE',
        'SUI',
        'WATER',
        'IRON',
        'WAVE',
        'NAM',
        'SAND',
        'BOAT',
        'BIRD',
        'WIND',
        'FISH',
        'MOSS',
        'RAINBOW',
        'BLUEONI',
        'SWAMP',
        'POISON',
        'WATERFALL',
        'A',
        'EXPERIMENT',
        'TIN',
        'ELECTRIC',
        'THUNDER',
        'ICE',
        'SNOW',
        'WOOD',
        'MOK',
        'LEAF',
        'HAA',
        'BULL',
        'BIGNOISE',
        'REDONI',
        'BLACKONI',
        'DEMON',
        'MAK',
        'TATSU',
        'DARK',
        'YAM',
        'PRISON',
        'FENCE',
        'RIDGE',
        'KBOSS',
        'ORE',
        'GRAVE',
        'ROCK',
        'DEPRESSION',
        'ROSE',
        'CHRYSANTHEMUM',
        'PEAK',
        'GACHA_BAKU',
        'GACHA_SHITSU',
        'GACHA_SADAME',
        'GACHA_AN',
        'GACHA_SO',
        'GACHA_TOU',
        'GACHA_HEN',
        'GACHA_ITSU',
        'GACHA_TOU2',
        'GACHA_SOU',
        'GACHA_KOU',
      ]),
    );
  });
});
