import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

type EnvMap = Record<string, string>;

const repoRoot = resolve(import.meta.dir, '..');
const bffRoot = resolve(repoRoot, '..', 'bff.shogi');
const bffEnvPath = resolve(bffRoot, '.env');
const outputPath = resolve(repoRoot, 'infra', 'terraform', 'bff.auto.tfvars');

const env = readEnvFile(bffEnvPath);
const values = collectValues(env);

writeFileSync(
  outputPath,
  [
    '# Generated by `bun run tf:sync-env`. Do not commit this file.',
    ...Object.entries(values).map(([key, value]) => `${key} = ${hclString(value)}`),
    '',
  ].join('\n'),
);

console.log(`[tf:sync-env] wrote ${outputPath}`);
if (Object.keys(values).length === 0) {
  console.warn(`[tf:sync-env] no matching Terraform values found in ${bffEnvPath}`);
}

function readEnvFile(path: string): EnvMap {
  if (!existsSync(path)) {
    throw new Error(`BFF env file not found: ${path}`);
  }

  const env: EnvMap = {};
  for (const rawLine of readFileSync(path, 'utf8').split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;

    const equalsIndex = line.indexOf('=');
    if (equalsIndex < 0) continue;

    const key = line.slice(0, equalsIndex).trim();
    const rawValue = line.slice(equalsIndex + 1).trim();
    env[key] = unquote(rawValue);
  }
  return env;
}

function collectValues(env: EnvMap): EnvMap {
  const values: EnvMap = {};
  const bffBaseUrl = first(env, [
    'MATCHING_BFF_BASE_URL',
    'BFF_BASE_URL',
    'EXPO_PUBLIC_API_BASE_URL',
  ]);
  if (bffBaseUrl) values.bff_base_url = bffBaseUrl;

  const internalToken = first(env, ['MATCHING_BFF_INTERNAL_TOKEN']);
  if (internalToken) values.matching_bff_internal_token = internalToken;

  const ticketSecret = first(env, ['MATCHING_TICKET_SECRET']);
  if (ticketSecret) values.matching_ticket_secret = ticketSecret;

  const missing = [
    ['bff_base_url', 'MATCHING_BFF_BASE_URL or EXPO_PUBLIC_API_BASE_URL'],
    ['matching_bff_internal_token', 'MATCHING_BFF_INTERNAL_TOKEN'],
    ['matching_ticket_secret', 'MATCHING_TICKET_SECRET'],
  ].filter(([key]) => !values[key]);

  if (missing.length > 0) {
    console.warn(
      [
        `[tf:sync-env] missing values in ${bffEnvPath}:`,
        ...missing.map(([, envKey]) => `  - ${envKey}`),
        'Add them to ../bff.shogi/.env, then rerun `bun run tf:sync-env`.',
      ].join('\n'),
    );
  }

  return values;
}

function first(env: EnvMap, keys: string[]): string | null {
  for (const key of keys) {
    const value = env[key]?.trim();
    if (value) return value;
  }
  return null;
}

function unquote(value: string): string {
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1);
  }
  return value;
}

function hclString(value: string): string {
  return JSON.stringify(value);
}
